### PR TITLE
Add tests for DashboardApiView and ApiTokenRequiredMixin

### PR DESCRIPTION
**Pull request by sumit4613**
#167 

100% coverage for `api` app.
image

### CODE REVIEW

**Comment by haaavk** [comment]
Nice work with 100% code coverage. 
Usually it's not a best idea to mix refactoring with other changes in one commit. 
Adding pure subjective code style changes may not be worth it. 
Some of them are likely to be undone next time I'll work on API.

**Comment by sumit4613** [comment]
Hey, @haaavk understood, I'll move tests and refactoring to separate commits.

**Comment by sumit4613** [comment]
Hey, @haaavk I have separated my changes into different commits. Please review.

Also, I'm hoping you guys don't have any issues using `black` for code formatting.

**Comment by haaavk** [comment]
Black is cool. I personally prefer to keep lines length under 100.
@milesmcc Are there any official code style rules for Shynet?

**Comment by sumit4613** [comment]
> Black is cool

✅ 🙌🏽 

> I personally prefer to keep lines length under 100.

I see, I keep them around 120.

> Are there any official code style rules for Shynet?

It'll be great if we can have official code style rules or a `.editerconfig` file.

**Comment by milesmcc** [comment]
Yeah @haaavk Black is what I prefer. We should codify this.

**Pull request merged**
