### PR TITLE
Fix performence in dashboard

### LINKED ISSUE #261: Performance issue
I have a medium-sized website that receives about 300k sessions and 1.5m pageviews per month. I switched to Shynet two weeks ago, but now I have noticed some performance issues with the chart. You can view the video demo here:

https://user-images.githubusercontent.com/96356/228383470-b59bf0d3-c26f-41eb-9f34-0f4dfdd98f92.mp4

After further investigation, I discovered that the issue may be due to the fact that the page is fully server-side rendered. The larger the website traffic, the more data needs to be loaded on the page. If the period is set to the last 30 days, the entire document initial download will be 1.9MB (after gzip compression):

image

A possible solution is to provide data through an API and replace the chart library with one that has better performance (like Apache EChart?).

### PR DESCRIPTION
**Pull request by haaavk**
Fix #261

### CODE REVIEW

**Comment by milesmcc** [comment]
Looks good; I need to test more robustly but I think it's on the right track. Would you mind posting some screenshots on the PR?

**Comment by haaavk** [comment]
I used sessions list template as starter. 

https://user-images.githubusercontent.com/818385/232865657-b36b2ac1-f72b-4d17-bfc2-ff90c422d4bc.mp4

**Comment by milesmcc** [comment]
Hmm, the video isn't working for me but it might be my computer.

I apologize for my slowness here. The underlying issue is that I got a new laptop, and I no longer have a good local development environment for Shynet where I can easily pull your changes and test them out. (And alas, we don't have a way to seed mock data.) This is my fault.

**Comment by haaavk** [comment]
Maybe this will work. 

https://user-images.githubusercontent.com/818385/233265840-5c291ea0-7637-49f9-9e45-50683487d4cb.mov

I had the same problem with mock data but I found management command call "demo". I made some cosmetic changes to it but it mostly works really good out of the box.

**Comment by milesmcc** [comment]
Good work.

**Pull request merged**
