### PR TITLE
Change snippet url to display current host

### LINKED ISSUE #98: Multiple hosts using same instance
So, I have a server with a few services that I share with my friends. All of us have our own domains and basically we want to have the same instance linked under different hostnames.

In the .env file, we can set `ALLOWED_HOSTS` to the allowed hostnames though we still need to set up one hostname that will be used in all of our scripts. In my opinion this single hostname is unneeded, as you can generate the tracking scripts based on the origin of dashboard the current user is using. 

The drawback of current approach is that, when you want to track 2 or more different websites, both websites will make requests to the same hostname, that means you can identify that all of them probably belong to the same person/entity. 

Generating scripts based of the hostname of dashboard deals with that problem.

### PR DESCRIPTION
**Pull request by wvffle**
Closes #98

### CODE REVIEW

**Comment by JuniorJPDJ** [comment]
Is `site.domain` used anywhere beyond that?
It probably should be removed entirely from config.

**Comment by wvffle** [comment]
It is in a few other templates and in .po files, though @milesmcc, should I replace them?

**Comment by JuniorJPDJ** [comment]
I just searched for it and it will be hard to replace occurrences in e-mail templates.
IMO It would be cool to remove those which are on-page tho.

**Comment by JuniorJPDJ** [comment]
This is probably also must-have:
https://github.com/milesmcc/shynet/blob/9d9d4a7b1e2644b058163b3df7168b5d7d0bb625/shynet/analytics/templates/analytics/scripts/page.js#L22

**Comment by wvffle** [comment]
hahahha, I did ```git commit -m "Remove `hostname` command"```

**Comment by JuniorJPDJ** [comment]
Are you sure that get_domain will work in email templates?

**Comment by wvffle** [comment]
request should be in the context: https://github.com/pennersr/django-allauth/blob/353386216b79f16709e97bb487c0bbbba2bc0c71/allauth/account/forms.py#L556

**Comment by CasperVerswijvelt** [comment]
@wvffle You can test if email content is correct by checking shynet logs. Email's are also outputted there

**Comment by wvffle** [comment]
Works well.

image

**Comment by JuniorJPDJ** [comment]
Supercool then :D

**Comment by milesmcc** [comment]
Well done.

**Review by milesmcc — APPROVED** [review]

**Comment by Henridv** [comment]
@wvffle 

How do I make sure the hostname is correct when running Shynet using Docker Compose?

When using the edge image from Docker Hub `request.get_host` seems to return `127.0.0.1`.

For now I reverted back to using version 0.10.0.

**Comment by JuniorJPDJ** [comment]
You quacked up something badly. Are you accessing it using http://127.0.0.1?
It should just return host from client's request.

**Comment by Henridv** [comment]
No, I'm accessing it from a regular domain.

If I go to the Manage tab to get the script code it also says `127.0.0.1`.

I'm running the container using docker compose, DNS is managed by Cloudflare and reverse proxy is nginx.

**Comment by JuniorJPDJ** [comment]
so this is probably misconfigured reverse proxy
try `tcpdump`ing requests coming to shynet container

**Comment by CasperVerswijvelt** [comment]
@Henridv I'm also using Docker Compose, nginx as reverse proxy and cloudflare as DNS, and it works correctly for me.

This is my reverse proxy setup:

```
server {

        server_name analytics.casperverswijvelt.be;

        include /etc/nginx/snippets/listen-ssl-cloudflare.conf;
        include /etc/nginx/snippets/cloudflare-allow.conf;

        location / {
                proxy_pass http://localhost:9595;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_hide_header 'x-frame-options';
                add_header X-Frame-Options ALLOWALL;
        }
}
```

**Comment by Henridv** [comment]
Thanks @CasperVerswijvelt 

This is the line I needed to add:
```
                proxy_set_header Host $host;
```

**Comment by milesmcc** [comment]
Great, glad this is fixed!

**Pull request merged**
