### PR TITLE
Predefined date ranges

### PR DESCRIPTION
**Pull request by haaavk**
Implements predefined ranges. It uses litepicker plugin.
I had to update litepicker version. It generated some extra work to run new litepicker.
Right now it looks like that.
Shynet  - Screenshot 2021-04-22 16:20:01

### CODE REVIEW

**Comment by CasperVerswijvelt** [comment]
I would maybe limit the options to 7 to not make the ui look weird with whitespace under the calendar

**Comment by milesmcc** [comment]
I agree with Casper. I think this is a positive change, but this is too many options. I would remove Today, Last 7 Days, and Last Year. (Those seem like the least useful to me.)

**Comment by haaavk** [comment]
I know it's not perfect. I'm not sure which to delete.
I can try to add this functionality without litepicker plugin.
Maybe add separete select next to date range input?

**Comment by milesmcc** [comment]
> I would remove Today, Last 7 Days, and Last Year. (Those seem like the least useful to me.)

Remove those?

**Comment by haaavk** [comment]
Done

**Comment by haaavk** [comment]
Yesterday range is useless due to #129. 
I replaced it with last 3 days.

**Pull request merged**
