### PR TITLE
Add hits to chart data

### PR DESCRIPTION
**Pull request by haaavk**
Linked to issue #140

### CODE REVIEW

**Comment by CasperVerswijvelt** [comment]
I would put this style on the 'bar' element to make it look a little spacier/better:
```
    top: 4px;
    left: 4px;
    height: calc(100% - 8px);
```

Maybe the width should also be based on the maximum amount of sessions for an element:
so in your screenshot from your first PR, 100% would be 66 in the browsers category
Shynet - progress 4 Screenshot 2021-05-07 09:52:04

And then maybe add those bars for country and operating system tables

**Comment by haaavk** [comment]
Sorry for lack of description in this PR. It is about hits data in sessions chart ( #140).
I think you should look at #139. There are some visual changes. We can talk about relative maximum there but I'm not a big fan of that.

**Comment by CasperVerswijvelt** [comment]
Oops indeed, I commented on the wrong PR, my bad.

**Comment by milesmcc** [comment]
Sweet. Merged (with just one small change).

**Comment by CasperVerswijvelt** [comment]
@haaavk I see that the cool looking gradient in the chart is gone, was it not possible to keep that with a combined chart like this?

**Comment by haaavk** [comment]
I don't know. Maybe it's possible.
In my opinion the most important thing in visualization is information. 
I like to keep it simple. Prettier chart isn't always better. 
For example 3d charts look nice but they are broken because of human perception.

**Comment by CasperVerswijvelt** [comment]
I agree with you, just tought the fading effect looked sleek and clean

**Pull request merged**
