### PR TITLE
Add an API

### PR DESCRIPTION
**Pull request by haaavk**
Usually I use Django REST Framework for API but in this case it could be overkill. 
If there are plans for full API I can rewrite it using DRF.
I added additional argument to service.get_core_stats() to return less data.
Tokens can be managed only from Django admin.

### CODE REVIEW

**Comment by milesmcc** [comment]
Just wanted to thank you for putting in the work for this PR. I think that before we add an API we should stabilize what our method for handling new "custom" events will be, so while I'm not ready to merge quite yet, I think we'll be there soon. Going to leave this open for the time being.

**Comment by milesmcc** [comment]
I propose we do this a bit differently: instead of having a complex API token setup, we simply add a "refreshable" API URL for every service (and in that URL is a token, but that token is tied to . In the service's management page, we can show that URL — along with a button to "regenerate" it. So for example, a service might have the following API URL: `https://shynet.com/api/service/286ff19d-6062-4033-ba83-d27f3c0f8ef8/?token=fjkhdslfhlkjdsahf` (where the `token` is stored inside the service model, and not another model).

This approach might be simpler because it allows us to not think about authorization as much, and it means that API tokens don't need to be coupled to users.

**Comment by haaavk** [comment]
It will work for me because I'm the only user of my shynet instance and I have only a few services.
The problem begins with multi-users instance with a dozen services.
For example there are 10 services and 5 users.
All users get access to all services so everybody gets 10 links and add them to some kind of a client. 
If we want to revoke the access to one user we need to refresh 10 tokens and resend them to 4 users and they need update them in a client.

**Comment by milesmcc** [comment]
I really want to keep Shynet small and focused, so maybe we just make it one refreshable API token per user instead? I really hesitate to introduce an additional model.

**Comment by haaavk** [comment]
One token per user is a good idea. I will apply changes. 
Should I add new view for API token or add it to security view or leave it to django admin?

**Comment by milesmcc** [comment]
Great. Let’s create a new view. We can also show the token on the service management page.

**Comment by haaavk** [comment]
Is there anything else I should change in this PR?

**Comment by milesmcc** [comment]
Alright, thanks again for making this PR. I just played around with it in my local environment, and I think we're nearly there! Still, there are a few more things we need:

- We need some documentation about how the API works. I mostly mean in places like GUIDE.md, but I also mean in the interface itself. Right now if you visit the API page, it has no context — we need to explain what is going on. For example, we should explain that this is the user's _personal_ API token.
- I don't think there should be a separate API tab. Perhaps we put it under "Account" or "Security"?
- I'm not sure it makes sense to put the API key without any context on the service management page. Instead, I think we should provide the link to the API where the user can access that service's information. I think that would be more directly useful.

I can make the interface look a bit more consistent/prettier myself before we merge, so don't worry too much about that. Thanks!

**Comment by haaavk** [comment]
I moved API token info to security tab and rename it to 'Personal API token'.
I added some basic API usage description to service management page and GUIDE.md.

**Comment by haaavk** [comment]
I tried to add django-cors-headers but it generated conflict in poetry.lock.
I'm not sure how to resolve this conflict.

**Comment by haaavk** [comment]
Sorry for this. Commit was lost in different branch somehow.

**Pull request merged**
