### PR TITLE
Show hourly chart when date range is 1 day

### LINKED ISSUE #127: Hourly data in graph when date range is 1 day
I think it would be neat to show a graph with hourly data when a date range of 1 day is selected, like plausible does (see screenshot). This would also make the predefeined date range of 'Today' more useful (from PR #123).

Can do PR for this if you like this idea.

image

### PR DESCRIPTION
**Pull request by CasperVerswijvelt**
Show hourly chart when date range is only 1 day, since that is the only time when the chart is completely useless (only 1 data point). I also set it so the graph is only drawn until the current time (not visible in screenshot since its 11 pm here now, last hour of the day). 

As @haaavk said in his comment, ideally this could be changed by user choice, but I think this is already a good start.

| Daily view (1 week range) | Hourly view (1 day range) |
|------------------|---------------|
|          image        |       image        |

closes #127

### CODE REVIEW

**Comment by milesmcc** [comment]
Great PR! I wonder — would it make sense to do this for any time period under one week? Or 3 days? Just because 2 days is only two data points, and perhaps we should show that on an hourly basis as well?

**Comment by haaavk** [comment]
I think 3 days and 2 days periods can benefit from hourly basis. I'm not so sure about one week.

**Comment by CasperVerswijvelt** [comment]
I agree that up to 3 days, the chart would benefit from hourly data points. 

Ideally tough, the user would get the option since there is  probably an overlap on what chart would be useful for specific date ranges. A future improvement would then be to allow hourly chart option for up to 7 days, allow daily chart from 3 days up to 356 days (?) and monthly option from 2 months up to unlimited months. Or something like that. I wanted to avoid having to add this for now though, but I will change it to show hourly chart starting from 3 day ranges.

**Comment by milesmcc** [comment]
Cool, thanks. Will test & merge for next release.

**Comment by haaavk** [comment]
What do you think about adding click event in daily view to show hourly view of the day?
The implementation in chart config could look like:
```javascript
events: {
    click: function(event, chartContext, config) {
        const day = config.config.series[config.seriesIndex].data[config.dataPointIndex].x
        window.location.href = `?startDate=${day}&endDate=${day}`
    },
},
```

**Comment by CasperVerswijvelt** [comment]
@haaavk  good idea! I changed your code a bit to use the `markerClick` event instead of the `click` one so it doesn't trigger when labels are clicked

**Pull request merged**
